import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {DatabaseSync} from 'node:sqlite';
import {generateKeyPair,SignJWT,createLocalJWKSet,exportJWK} from 'jose';
import {verifyAdmin} from '../src/auth.js';
import worker,{handleAdmin,validateExample} from '../src/worker.js';
const origin='https://dev.mathdic.bang-academy.com';
const db=new DatabaseSync(':memory:');db.exec(await readFile('migrations/0001_examples.sql','utf8'));
const env={ADMIN_HOST:'dev.mathdic.bang-academy.com',ADMIN_EMAIL:'renobang@gmail.com',ACCESS_AUD:'test-audience',ACCESS_TEAM_DOMAIN:'https://test.cloudflareaccess.com',CONTENT_DB:{prepare(sql){return {bind(...params){return {async run(){const r=db.prepare(sql).run(...params);return {meta:{changes:r.changes}}}}},async all(){return {results:db.prepare(sql).all()}}}}},ASSETS:{async fetch(request){return Response.json(JSON.parse(await readFile('public/data/notes.json','utf8')))}}};
const {publicKey,privateKey}=await generateKeyPair('RS256');const jwk=await exportJWK(publicKey);jwk.kid='test';const keys=createLocalJWKSet({keys:[jwk]});
const token=(email=env.ADMIN_EMAIL,aud=env.ACCESS_AUD,expires='5m')=>new SignJWT({email}).setProtectedHeader({alg:'RS256',kid:'test'}).setIssuer(env.ACCESS_TEAM_DOMAIN).setAudience(aud).setSubject('admin-test').setIssuedAt().setExpirationTime(expires).sign(privateKey);
const req=t=>new Request(origin+'/admin/',{headers:{'cf-access-jwt-assertion':t}});
assert.equal(await verifyAdmin(req(await token()),env,keys),env.ADMIN_EMAIL);
for(const t of [await token('other@example.com'),await token(env.ADMIN_EMAIL,'other-app'),await token(env.ADMIN_EMAIL,env.ACCESS_AUD,'-1s'),'forged.token.value'])await assert.rejects(verifyAdmin(req(t),env,keys));
for(const path of ['/admin','/admin/','/admin/admin.js','/admin/api/examples'])assert.equal((await worker.fetch(new Request(origin+path),env)).status,403);
assert.equal((await worker.fetch(new Request('https://mathdic-development.renobang.workers.dev/admin/'),env)).status,403);
assert.throws(()=>validateExample({revision:0,prompt:'Question',latex:'\\badcommand',explanation:'Answer'}));
const body={id:'absolute-value',revision:0,prompt:'A point is −13 units from zero. Find its distance.',latex:'\\lvert-13\\rvert=13',explanation:'Its distance from zero is 13 units.'};
const put=(value=body,from=origin)=>new Request(origin+'/admin/api/examples',{method:'PUT',headers:{origin:from,'Content-Type':'application/json','X-MathDic-Admin':'1'},body:JSON.stringify(value)});
assert.equal((await handleAdmin(put(body,'https://evil.example'),env,env.ADMIN_EMAIL)).status,403);
assert.equal((await handleAdmin(put({...body,id:'__proto__'}),env,env.ADMIN_EMAIL)).status,404);
assert.equal((await handleAdmin(put(),env,env.ADMIN_EMAIL)).status,200);
assert.equal((await handleAdmin(put(),env,env.ADMIN_EMAIL)).status,409);
assert.equal((await handleAdmin(put({...body,revision:1,latex:'13=13'}),env,env.ADMIN_EMAIL)).status,200);
assert.equal(db.prepare('SELECT count(*) n FROM example_history').get().n,2);
const publicData=await (await worker.fetch(new Request(origin+'/data/notes.json'),env)).json();
assert.equal(publicData['absolute-value'].latex,'13=13');assert.equal(publicData['absolute-value'].diagramSpec,null);assert.equal(publicData['absolute-value'].updated_by,undefined);
const adminData=await (await handleAdmin(new Request(origin+'/admin/api/examples'),env,env.ADMIN_EMAIL)).json();assert.equal(adminData.examples.find(n=>n.id===body.id).revision,2);
assert.equal(db.prepare('SELECT count(*) n FROM examples').get().n,1);
db.close();console.log('PASS: signed JWT validation, email/audience/expiry checks, anonymous and alternate-host denial, CSRF, LaTeX validation, shared save, conflict detection, history, student read.');
